server:
  port: 9999

spring:
  application:
    name: CONSUMER-SERVICE

eureka:
  cliente:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
